variables:
  NAMESPACE: "aws"
  AWS_ACCOUNT: "514038909166"
  AWS_DEFAULT_REGION: "eu-west-2"
  ARTEFACT: "cloud-carbon-footprint.tar.gz"

default:
    tags:
      - LSEG
 
include:
  - project: ci/stable/security/vault/vault-integrator
    ref: 2.0.0
    file:
      - "templates/vault-integrator.yml"

image: node:16.17.0

stages:
  - lseg-vault
  - build
  - upload-to-s3

.rules-config:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' 
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'
      variables:
        ENV: "dev"
  
1-vault-aws-auth:
  stage: lseg-vault
  extends: [.vault-aws-auth, .rules-config]
 
build:
  stage: build
  extends:
    - .rules-config
  script:
    - yarn install     
    - tar --exclude=.git -zcf "../${ARTEFACT}" . 
    - cp ../${ARTEFACT} .
  needs: [1-vault-aws-auth]
  dependencies: [1-vault-aws-auth]
  artifacts:
    when: on_success
    paths:
      - "$CI_PROJECT_DIR/${ARTEFACT}"

upload-to-s3:
  stage: upload-to-s3
  when: manual
  extends:
  - .rules-config
  image:
    name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/amazon/aws-cli:2.10.0
  script:
    - aws s3 cp "${ARTEFACT}" "s3://emistrac-${ENV}-carbon-emission-reports-euwest2-s3/artifacts/${ARTEFACT}"
  needs: [1-vault-aws-auth, build]
  dependencies: [1-vault-aws-auth, build]




